version: "3.8"

networks:
  docker-event-metrics-net:

services:
  swarm:
    image: rjchicago/docker-event-metrics:${VERSION:-latest}
    networks:
      - docker-event-metrics-net
    environment:
      ENV: "${ENV:-local}"
      OPTIONS: '{"filter": {"scope": "swarm"}}'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8076:3000"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  local:
    image: rjchicago/docker-event-metrics:${VERSION:-latest}
    networks:
      - docker-event-metrics-net
    environment:
      ENV: "${ENV:-local}"
      INSTANCE: "{{.Node.Hostname}}"
      OPTIONS: '{"filter": {"scope": "local"}}'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8077:3000"
    deploy:
      mode: global

  prometheus:
    image: prom/prometheus
    networks:
      - docker-event-metrics-net
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    deploy:
      replicas: 1
  
  test:
    image: alpine
    command: tail -f /dev/null
    networks:
      - docker-event-metrics-net
    deploy:
      replicas: 1
