name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        "REGISTRY_USER=${{ secrets.DOCKERHUB_USER }}"
        "REGISTRY_PASSWORD=${{ secrets.DOCKERHUB_TOKEN }}"
        sh .ci/set-ci-vars.sh
        sh .ci/build-and-push.sh
